import { useEffect, useState } from "react";
import { api, type Campaign, type DetectedDonation } from "../lib/api";

export default function GalleryPage() {
  const [campaign, setCampaign] = useState<Campaign | null>(null);
  const [donations, setDonations] = useState<DetectedDonation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([api.getCampaign(), api.getDonations()])
      .then(([c, d]) => {
        setCampaign(c);
        setDonations(d);
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-20 text-center text-slate-400">
        Loading gallery…
      </div>
    );
  }

  const minted = donations.filter((d) => d.status === "minted");

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 py-10 space-y-8">
      <div>
        <div className="flex flex-wrap items-center gap-3">
          <h1 className="text-2xl font-bold text-white">Proof Gallery</h1>
          <span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs font-semibold tracking-wide text-amber-300">
            DEMO MODE
          </span>
        </div>
        <p className="mt-1 text-slate-400 text-sm">
          Contribution proofs generated by ShieldGive. Demo proofs are local mock records; live Solana proofs will appear here when on-chain minting is enabled.
        </p>
      </div>

      {/* Totals */}
      <section className="grid sm:grid-cols-3 gap-4">
        <div className="card p-5">
          <p className="text-xs text-slate-400">Total Raised</p>
          <p className="mt-1 text-2xl font-semibold text-shield-300 font-mono">
            {campaign?.totalRaisedZEC.toFixed(4) ?? "0.0000"} ZEC
          </p>
        </div>
        <div className="card p-5">
          <p className="text-xs text-slate-400">Donations Detected</p>
          <p className="mt-1 text-2xl font-semibold text-white font-mono">
            {campaign?.donationCount ?? 0}
          </p>
        </div>
        <div className="card p-5">
          <p className="text-xs text-slate-400">Demo Proofs</p>
          <p className="mt-1 text-2xl font-semibold text-white font-mono">
            {minted.length}
          </p>
        </div>
      </section>

      {/* NFT list */}
      <section className="card overflow-hidden">
        <div className="border-b border-slate-800 px-6 py-4">
          <h2 className="font-semibold text-white">Contribution Proofs</h2>
        </div>

        {minted.length === 0 ? (
          <div className="px-6 py-12 text-center text-slate-500 text-sm">
            No demo proofs yet. Register a wallet and run the demo donation pipeline
            to create the first proof.
          </div>
        ) : (
          <ul className="divide-y divide-slate-800">
            {minted.map((d) => (
              <li
                key={d.id}
                className="px-6 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="badge bg-amber-500/15 text-amber-300">
                      Demo Mint
                    </span>
                    <span className="text-sm font-mono text-slate-300">
                      {d.amountZEC} ZEC
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 font-mono truncate max-w-md">
                    Demo proof: {d.nftMintAddress}
                  </p>
                  {d.solanaWallet && (
                    <p className="text-xs text-slate-600 font-mono truncate max-w-md">
                      → {d.solanaWallet.slice(0, 6)}…{d.solanaWallet.slice(-4)}
                    </p>
                  )}
                </div>
                <time className="text-xs text-slate-500 shrink-0">
                  {new Date(d.detectedAt).toLocaleString()}
                </time>
              </li>
            ))}
          </ul>
        )}
      </section>

      <p className="text-center text-xs text-slate-600">
        Wallet addresses are partially redacted in the public gallery. The demo gallery does not create a real Solana NFT. Live on-chain proof status will be shown only after real minting is enabled.
      </p>
    </div>
  );
}
