import { useEffect, useState } from "react";
import { api, type Campaign, type DetectedDonation } from "../lib/api";

export default function GalleryPage() {
  const [campaign, setCampaign] = useState<Campaign | null>(null);
  const [donations, setDonations] = useState<DetectedDonation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([api.getCampaign(), api.getDonations()])
      .then(([c, d]) => {
        setCampaign(c);
        setDonations(d);
      })
      .catch((err) => setError(err instanceof Error ? err.message : "Backend unavailable"))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return <div className="mx-auto max-w-4xl px-4 py-20 text-center text-slate-400">Loading gallery…</div>;
  }

  if (error) {
    return (
      <div className="mx-auto max-w-4xl px-4 py-20 text-center">
        <h1 className="text-xl font-semibold text-white">Proof Gallery unavailable</h1>
        <p className="mt-2 text-sm text-amber-300">{error}</p>
        <p className="mt-2 text-xs text-slate-500">The live backend did not respond. Demo data is not substituted automatically.</p>
      </div>
    );
  }

  const minted = donations.filter((d) => d.status === "minted");
  const demoProofs = minted.filter((d) => d.nftMintAddress?.startsWith("mint_"));
  const liveProofs = minted.filter((d) => !!d.nftMintAddress && !d.nftMintAddress.startsWith("mint_"));
  const hasLiveProof = liveProofs.length > 0;

  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 py-10 space-y-8">
      <div>
        <div className="flex flex-wrap items-center gap-3">
          <h1 className="text-2xl font-bold text-white">Proof Gallery</h1>
          <span className={`rounded-full border px-3 py-1 text-xs font-semibold tracking-wide ${hasLiveProof ? "border-shield-500/30 bg-shield-500/10 text-shield-300" : "border-amber-500/30 bg-amber-500/10 text-amber-300"}`}>
            {hasLiveProof ? "LIVE ON-CHAIN" : "AWAITING LIVE PROOF"}
          </span>
        </div>
        <p className="mt-1 text-slate-400 text-sm">
          Contribution proofs generated by ShieldGive. Live proofs are identified by their Solana mint address; demo records are explicitly marked.
        </p>
      </div>

      <section className="grid sm:grid-cols-3 gap-4">
        <div className="card p-5"><p className="text-xs text-slate-400">Total Raised</p><p className="mt-1 text-2xl font-semibold text-shield-300 font-mono">{campaign?.totalRaisedZEC.toFixed(4) ?? "0.0000"} ZEC</p></div>
        <div className="card p-5"><p className="text-xs text-slate-400">Donations Detected</p><p className="mt-1 text-2xl font-semibold text-white font-mono">{campaign?.donationCount ?? 0}</p></div>
        <div className="card p-5"><p className="text-xs text-slate-400">Proofs</p><p className="mt-1 text-2xl font-semibold text-white font-mono">{minted.length}</p><p className="mt-1 text-[11px] text-slate-600">{demoProofs.length} demo · {liveProofs.length} live</p></div>
      </section>

      <section className="card overflow-hidden">
        <div className="border-b border-slate-800 px-6 py-4"><h2 className="font-semibold text-white">Contribution Proofs</h2></div>
        {minted.length === 0 ? (
          <div className="px-6 py-12 text-center text-slate-500 text-sm">No minted proofs yet. Complete a live donation flow to create the first on-chain proof.</div>
        ) : (
          <ul className="divide-y divide-slate-800">
            {minted.map((d) => (
              <li key={d.id} className="px-6 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className={d.nftMintAddress?.startsWith("mint_") ? "badge bg-amber-500/15 text-amber-300" : "badge bg-shield-500/15 text-shield-300"}>{d.nftMintAddress?.startsWith("mint_") ? "Demo Proof" : "Live On-chain"}</span>
                    <span className="text-sm font-mono text-slate-300">{d.amountZEC} ZEC</span>
                  </div>
                  <p className="text-xs text-slate-500 font-mono truncate max-w-md">{d.nftMintAddress?.startsWith("mint_") ? "Demo proof: " : "Solana mint: "}{d.nftMintAddress}</p>
                  {d.solanaWallet && <p className="text-xs text-slate-600 font-mono truncate max-w-md">→ {d.solanaWallet.slice(0, 6)}…{d.solanaWallet.slice(-4)}</p>}
                </div>
                <time className="text-xs text-slate-500 shrink-0">{new Date(d.detectedAt).toLocaleString()}</time>
              </li>
            ))}
          </ul>
        )}
      </section>

      <p className="text-center text-xs text-slate-600">Wallet addresses are partially redacted in the public gallery. Live on-chain proof status is shown only when a real Solana mint address is recorded by the backend.</p>
    </div>
  );
}
